### ISSUE TITLE
defualt in switch

### ISSUE THREAD

**Issue by LiuIhor** [okutnii/testHandler_j17#2]
https://github.com/okutnii/testHandler_j17/blob/87260851b409787b7d009971319623ccbfa240bc/src/main/java/easyXO/Main.java#L101
Why use default?

**Comment by okutnii** [comment]
in case enum was changed so some other level was added, recognition of its behavior will lead to an exception

**Comment by LiuIhor** [comment]
But now "default" is non-functional?

**Comment by okutnii** [comment]
in switch statement we define bot's behavior. if there is no matches, it throws exception.

**Comment by okutnii** [comment]
close please if i clarified this
