### ISSUE TITLE
The return value

### ISSUE THREAD

**Issue by LiuIhor** [okutnii/testHandler_j17#3]
https://github.com/okutnii/testHandler_j17/blob/87260851b409787b7d009971319623ccbfa240bc/src/main/java/extra/banking/BankSystem.java#L44-L57

The return value in not used anywhere. You can do this method 'void'.

**Comment by okutnii** [comment]
Right. I wasn't sure about methods usage, so I've defined return type.

**Comment by okutnii** [comment]
done
